# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  events_mssql:

services:
  restApi:
    container_name: EIMS
    image: EIMS_api
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    build:
      context: .
      dockerfile: src/RestApi/Dockerfile

  EIMS:
    container_name: EIMS_Job
    image: EIMS_api
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
    build:
      context: .
      dockerfile: src/ScheduleJob/Dockerfile

  mssql:
    # platform: linux/amd64
    # image: mcr.microsoft.com/mssql/server
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    volumes:
      - events_mssql:/var/opt/mssql
      - ./setup.sql:/usr/config/setup.sql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw@rd
      - MSSQL_PID=Developer
      - MSSQL_DB=events_service
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=Passw@rd
      - MSSQL_DB_AUDIT_LOG=events_service_audit_log

  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - /data/redis-data:/data
